pipeline {
    agent any

    environment {
        // Define global environment variables if needed
        BRANCH = 'main' // Change branch if needed
        REPO_URL = 'https://github.com/mdabraralam/impart-buddies-sample-01.git'
        DOCKER_IMAGE = 'mdabraralam/impart-bodies-sample-service'
        IMAGE_TAG = "0.0.1-SNAPSHOT"
    } 
    
    tools {
        maven 'Maven-3.8.6' // Use the exact name defined in Jenkins
    }

    stages {
        
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                checkout([$class: 'GitSCM', 
                    branches: [[name: "*/${BRANCH}"]],
                    userRemoteConfigs: [[url: "${REPO_URL}"]]
                ])
            }
        }

        // stage('Build') {
        //     steps {
        //         echo 'Building project...'
        //         bat 'mvn -f impart-buddies-sample-01/pom.xml clean install' // Or use 'mvn clean install' for Maven
        //     }
        // }
        
        stage('Test') {
            steps {
                echo 'Running tests...'
                bat 'mvn -f impart-buddies-sample-01/pom.xml test' // Or 'mvn test' for Maven
            }
        }
        
        stage('Docker Build') {
            steps {
                dir('eureka-server') {
                    echo '🐳 Building Docker Image...'
                    // Docker build command using bat
                    bat "docker build -t %DOCKER_IMAGE%:%IMAGE_TAG% ."
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Docker image built and pushed successfully.'
        }
        failure {
            echo 'Docker image build failed. Please check the logs.'
        }
    }
}
